### PR TITLE
Update kernel to 4.4.10 with Docker settings

### PR DESCRIPTION
**Pull request by DieterReuter**
* [x] Update to kernel 4.4.10
* [x] pin to a specific kernel git commit, eg. https://github.com/raspberrypi/linux/commit/52261e73a34f9ed7f1d049902842895a2c433a50

### CODE REVIEW

**Comment by StefanScherer** [comment]
@DieterReuter the problem with the CircleCI timeout can be fixed with https://github.com/hypriot/rpi-kernel/commit/d95161bfc94f2c0cf9750b88d7558683d69ff801
We should cherry-pick that into this PR.

**Comment by DieterReuter** [comment]
Thanks, I'm testing it locally right now.

**Comment by DieterReuter** [comment]
@StefanScherer your fix works great. A local build which needs 72min before is now down to 25min.

**Comment by StefanScherer** [comment]
Oh, build https://circleci.com/api/v1/project/hypriot/rpi-kernel/17/output/10/0?file=true had problems.

```
dpkg-source: info: building linux-4.4.10-hypriotos-v7+ in linux-4.4.10-hypriotos-v7+_4.4.10-hypriotos-v7+-1.dsc
dpkg-genchanges: including full source code in upload
+ /var/kernel_build/cache/tools/mkimage/mkknlimg /var/kernel_build/cache/linux-kernel/arch/arm/boot/Image /var/kernel_build/results/kernel-20160519-200324/rpi2_3/kernel7.img
scripts/compile_kernel.sh: line 141: /var/kernel_build/cache/tools/mkimage/mkknlimg: No such file or directory
```

**Comment by StefanScherer** [comment]
https://github.com/raspberrypi/tools/tree/master/mkimage
tools has been removed.

**Comment by StefanScherer** [comment]
```
The mkknlimg and knlinfo utilities are now found in the scripts directory
of the Linux tree, where they are covered by the kernel licence.

Note also that the firmware shipped with 4.4 kernels now assumes the kernel
is Device Tree-capable unless there is a trailer to say otherwise, meaning
that these tools aren't needed for most situations.
```

**Comment by StefanScherer** [comment]
LGTM

**Pull request merged**
